#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable

-mode(compile).

main([LogFile]) ->
    code:add_paths([
                    "deps/eleveldb/ebin",
                    "ebin"]),
    wsdemo_logger:foldl(fun(Term, _) -> 
                                io:format("~w~n", [Term])
                        end, '_',
                        LogFile),
    ok;
main(_) ->
    usage().
                
usage() ->
    io:format("usage: ~n"
     "cat_stats LogFile::string()",[]).

    
