build: dist/wsdemo-1.0-SNAPSHOT.zip wsdemo-1.0-SNAPSHOT

clean:
	rm -rf wsdemo-1.0-SNAPSHOT/
	rm dist/wsdemo-1.0-SNAPSHOT.zip

wsdemo-1.0-SNAPSHOT:
	unzip dist/wsdemo-1.0-SNAPSHOT.zip

dist/wsdemo-1.0-SNAPSHOT.zip:
	../play-2.0.1/play dist



